/*
 *  Config
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
 *
 * Copyright (C) 2017 EPAM Systems Inc.
 */

#ifndef SRC_CONFIG_HPP_
#define SRC_CONFIG_HPP_

#include <exception>
#include <libconfig.h++>
#include <memory>
#include <string>
#include <xt/Log.hpp>

#include "IlmObject.hpp"

/*******************************************************************************
 * @defgroup config Config
 * Config related classes.
 ******************************************************************************/

/*******************************************************************************
 * Exception generated by Config class.
 * @ingroup config
 ******************************************************************************/
class ConfigException : public std::exception {
public:
    explicit ConfigException(const std::string& msg) : mMsg(msg){};
    virtual ~ConfigException() {}

    /**
     * returns error message
     */
    const char* what() const throw() { return mMsg.c_str(); };

private:
    std::string mMsg;
};

/*******************************************************************************
 * Display configuration
 * @ingroup config
 ******************************************************************************/
struct DisplayConfig {
    std::string name;
    t_ilm_display id;
};

/*******************************************************************************
 * Layer configuration
 * @ingroup config
 ******************************************************************************/
struct LayerConfig {
    std::string name;
    t_ilm_layer id;
    bool create;
    std::string display;
    t_ilm_uint width;
    t_ilm_uint height;
    IlmRectangle source;
    IlmRectangle destination;
    int order;
    t_ilm_bool visibility;
    t_ilm_float opacity;
};

/*******************************************************************************
 * Surface configuration
 * @ingroup config
 ******************************************************************************/
struct SurfaceConfig {
    std::string name;
    t_ilm_surface id;
    std::string layer;
    t_ilm_uint width;
    t_ilm_uint height;
    IlmRectangle source;
    IlmRectangle destination;
    int order;
    t_ilm_bool visibility;
    t_ilm_float opacity;
};

/*******************************************************************************
 * EventCreate configuration
 * @ingroup config
 ******************************************************************************/
struct EventCreateConfig {
    std::string object;
    std::string name;
};

/*******************************************************************************
 * EventDestroy configuration
 * @ingroup config
 ******************************************************************************/
struct EventDestroyConfig {
    std::string object;
    std::string name;
};

/*******************************************************************************
 * EventUser configuration
 * @ingroup config
 ******************************************************************************/
struct EventUserConfig {
    uint32_t id;
};

/*******************************************************************************
 * ActionSource configuration
 * @ingroup config
 ******************************************************************************/
struct ActionSourceConfig {
    std::string object;
    std::string name;
    IlmRectangle source;
};

/*******************************************************************************
 * ActionDestination configuration
 * @ingroup config
 ******************************************************************************/
struct ActionDestinationConfig {
    std::string object;
    std::string name;
    IlmRectangle destination;
};

/*******************************************************************************
 * ActionParent configuration
 * @ingroup config
 ******************************************************************************/
struct ActionParentConfig {
    std::string object;
    std::string name;
    std::string parent;
};

/*******************************************************************************
 * ActionOrder configuration
 * @ingroup config
 ******************************************************************************/
struct ActionOrderConfig {
    std::string object;
    std::string name;
    int order;
};

/*******************************************************************************
 * ActionVisibility configuration
 * @ingroup config
 ******************************************************************************/
struct ActionVisibilityConfig {
    std::string object;
    std::string name;
    t_ilm_bool visibility;
};

/*******************************************************************************
 * ActionOpacity configuration
 * @ingroup config
 ******************************************************************************/
struct ActionOpacityConfig {
    std::string object;
    std::string name;
    t_ilm_float opacity;
};

/*******************************************************************************
 * Provides different settings for backends.
 * @ingroup config
 ******************************************************************************/
class Config {
public:
    /**
     * @param fileName
     */
    Config(const std::string& fileName);

    int getDisplaysCount() const { return mDisplaysCount; }
    void getDisplayConfig(int index, DisplayConfig& config);

    int getLayersCount() const { return mLayersCount; }
    void getLayerConfig(int index, LayerConfig& config);

    int getSurfacesCount() const { return mSurfacesCount; }
    void getSurfaceConfig(int index, SurfaceConfig& config);

    int getEventsCount() const { return mEventsCount; }
    void getEventName(int index, std::string& name);
    void getEventCreateConfig(int index, EventCreateConfig& config);
    void getEventDestroyConfig(int index, EventDestroyConfig& config);
    void getEventUserConfig(int index, EventUserConfig& config);

    int getActionsCount(int eventIndex) const;
    void getActionName(int eventIndex, int actionIndex, std::string& name);
    void getActionSourceConfig(int eventIndex, int actionIndex,
                               ActionSourceConfig& config);
    void getActionDestinationConfig(int eventIndex, int actionIndex,
                                    ActionDestinationConfig& config);
    void getActionParentConfig(int eventIndex, int actionIndex,
                               ActionParentConfig& config);
    void getActionOrderConfig(int eventIndex, int actionIndex,
                              ActionOrderConfig& config);
    void getActionVisibilityConfig(int eventIndex, int actionIndex,
                                   ActionVisibilityConfig& config);
    void getActionOpacityConfig(int eventIndex, int actionIndex,
                                ActionOpacityConfig& config);

private:
    const char* cDefaultCfgName = "dm.cfg";

    xt::Log mLog;
    libconfig::Config mConfig;

    int mDisplaysCount;
    int mLayersCount;
    int mSurfacesCount;
    int mEventsCount;

    int readSectionCount(const std::string& name) const;
    void readRectangle(libconfig::Setting& setting, IlmRectangle& rect);
};

typedef std::shared_ptr<Config> ConfigPtr;

#endif /* SRC_CONFIG_HPP_ */
